module.exports = [
  { kubikName: 'lists.get', apiName: 'lists.get' },
  { kubikName: 'lists.add', apiName: 'lists.add' },
  { kubikName: 'lists.update', apiName: 'lists.update' },
  { kubikName: 'lists.delete', apiName: 'lists.delete' },
  { kubikName: 'lists.get_members', apiName: 'lists.get_members' },
  { kubikName: 'lists.get_unsubscribed', apiName: 'lists.get_unsubscribed' },
  { kubikName: 'lists.get_complaints', apiName: 'lists.get_complaints' },
  { kubikName: 'lists.member_activity', apiName: 'lists.member_activity' },
  { kubikName: 'lists.upload', apiName: 'lists.upload' },
  { kubikName: 'lists.add_member', apiName: 'lists.add_member' },
  { kubikName: 'lists.add_member_batch', apiName: 'lists.add_member_batch' },
  { kubikName: 'lists.update_member', apiName: 'lists.update_member' },
  { kubikName: 'lists.delete_member', apiName: 'lists.delete_member' },
  { kubikName: 'lists.unsubscribe_member', apiName: 'lists.unsubscribe_member' },
  { kubikName: 'lists.move_member', apiName: 'lists.move_member' },
  { kubikName: 'lists.copy_member', apiName: 'lists.copy_member' },
  { kubikName: 'lists.add_merge', apiName: 'lists.add_merge' },
  { kubikName: 'lists.update_merge', apiName: 'lists.update_merge' },
  { kubikName: 'lists.delete_merge', apiName: 'lists.delete_merge' },
  { kubikName: 'lists.last_status', apiName: 'lists.last_status' },
  { kubikName: 'lists.get_import_history', apiName: 'lists.get_import_history' },
  { kubikName: 'lists.check_email', apiName: 'lists.check_email' }
]
